# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: assignments.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61ssignments.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x02\n\x06\x43ourse\x12\x11\n\tcourse_id\x18\x01 \x01(\x03\x12\x13\n\x0b\x63ourse_name\x18\x02 \x01(\t\x12\x0f\n\x07\x63redits\x18\x03 \x01(\x03\x12.\n\nstart_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_date\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1d\n\x15scheduled_course_time\x18\x06 \x01(\t\x12#\n\x11\x65nrolled_students\x18\x07 \x03(\x0b\x32\x08.Student\x12\"\n\x10\x64ropped_students\x18\x08 \x03(\x0b\x32\x08.Student\x12#\n\x06grades\x18\t \x03(\x0b\x32\x13.Course.GradesEntry\x1a-\n\x0bGradesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"~\n\x07Student\x12\x12\n\nstudent_id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\x05\x65mail\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x17\n\x0f\x63redit_capacity\x18\x04 \x01(\x03\x12\x1a\n\x12ongoing_courses_id\x18\x05 \x03(\x03\x42\x08\n\x06_email\"(\n\x15\x43reateStudentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"(\n\x15UpdateStudentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x62\n\x08Students\x12*\n\x06\x43reate\x12\x08.Student\x1a\x16.CreateStudentResponse\x12*\n\x06Update\x12\x08.Student\x1a\x16.UpdateStudentResponseb\x06proto3')



_COURSE = DESCRIPTOR.message_types_by_name['Course']
_COURSE_GRADESENTRY = _COURSE.nested_types_by_name['GradesEntry']
_STUDENT = DESCRIPTOR.message_types_by_name['Student']
_CREATESTUDENTRESPONSE = DESCRIPTOR.message_types_by_name['CreateStudentResponse']
_UPDATESTUDENTRESPONSE = DESCRIPTOR.message_types_by_name['UpdateStudentResponse']
Course = _reflection.GeneratedProtocolMessageType('Course', (_message.Message,), {

  'GradesEntry' : _reflection.GeneratedProtocolMessageType('GradesEntry', (_message.Message,), {
    'DESCRIPTOR' : _COURSE_GRADESENTRY,
    '__module__' : 'assignments_pb2'
    # @@protoc_insertion_point(class_scope:Course.GradesEntry)
    })
  ,
  'DESCRIPTOR' : _COURSE,
  '__module__' : 'assignments_pb2'
  # @@protoc_insertion_point(class_scope:Course)
  })
_sym_db.RegisterMessage(Course)
_sym_db.RegisterMessage(Course.GradesEntry)

Student = _reflection.GeneratedProtocolMessageType('Student', (_message.Message,), {
  'DESCRIPTOR' : _STUDENT,
  '__module__' : 'assignments_pb2'
  # @@protoc_insertion_point(class_scope:Student)
  })
_sym_db.RegisterMessage(Student)

CreateStudentResponse = _reflection.GeneratedProtocolMessageType('CreateStudentResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATESTUDENTRESPONSE,
  '__module__' : 'assignments_pb2'
  # @@protoc_insertion_point(class_scope:CreateStudentResponse)
  })
_sym_db.RegisterMessage(CreateStudentResponse)

UpdateStudentResponse = _reflection.GeneratedProtocolMessageType('UpdateStudentResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESTUDENTRESPONSE,
  '__module__' : 'assignments_pb2'
  # @@protoc_insertion_point(class_scope:UpdateStudentResponse)
  })
_sym_db.RegisterMessage(UpdateStudentResponse)

_STUDENTS = DESCRIPTOR.services_by_name['Students']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COURSE_GRADESENTRY._options = None
  _COURSE_GRADESENTRY._serialized_options = b'8\001'
  _COURSE._serialized_start=55
  _COURSE._serialized_end=402
  _COURSE_GRADESENTRY._serialized_start=357
  _COURSE_GRADESENTRY._serialized_end=402
  _STUDENT._serialized_start=404
  _STUDENT._serialized_end=530
  _CREATESTUDENTRESPONSE._serialized_start=532
  _CREATESTUDENTRESPONSE._serialized_end=572
  _UPDATESTUDENTRESPONSE._serialized_start=574
  _UPDATESTUDENTRESPONSE._serialized_end=614
  _STUDENTS._serialized_start=616
  _STUDENTS._serialized_end=714
# @@protoc_insertion_point(module_scope)
