version: "3.7"

services:
  # redis:
  #   restart: always
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "0.0.0.0:6379:6379"
  #   volumes:
  #     - ./grpc_app/redis_persistence:/data

  # redis_backup:
  #   restart: always
  #   image: redis:latest
  #   container_name: redis_backup
  #   ports:
  #     - "0.0.0.0:6380:6379"
  #   volumes:
  #     - ./grpc_app/redis_persistence_backup:/data

  sc_service:
    build:
      context: ./grpc_app
      dockerfile: Dockerfile
    image: sc_service:v1
    container_name: sc_service
    restart: always
    