version: "3.8"

services:

  # sc_service:
    # build:
    #   context: ./grpc_app
    #   dockerfile: Dockerfile
    # image: sc_service
    # container_name: sc_service
    # ports:
    #   - "1024"
    # depends_on:
    #   - redis
    # env_file:
    #   - ./grpc_app/config.py
    # restart: always

  redis:
    restart: always
    image: redis:latest
    container_name: redis
    command: redis-server --save 60 1
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - ./grpc_app/db:/data
    environment:
      - REDIS_REPLICATION_MODE=master

  redis_backup:
    restart: always
    image: redis:latest
    container_name: redis_backup
    depends_on:
      - redis
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_PORT_NUMBER=6379
    volumes:
      - ./grpc_app/db_backup:/data

    